spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=school;encrypt=true;trustServerCertificate=true;
    username: sa
    password: 12345
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update  # Options: none, update, create, create-drop
        dialect: org.hibernate.dialect.SQLServer2012Dialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8081
